# Generated by Django 3.0 on 2021-11-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_water',
            fields=[
                ('SW_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='设备编号：')),
                ('SW_tem', models.CharField(max_length=50, verbose_name='温度：')),
                ('SW_pre', models.CharField(max_length=25, verbose_name='水压')),
                ('SW_inwater', models.CharField(max_length=25, verbose_name='单位进水量')),
                ('SW_outwater', models.CharField(max_length=25, verbose_name='单位出水量')),
                ('SW_tur', models.CharField(max_length=20, verbose_name='水体浑浊度')),
            ],
        ),
    ]
