# Generated by Django 3.0 on 2021-12-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_sensor',
            fields=[
                ('SW_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='设备ID：')),
                ('SW_num', models.CharField(max_length=50, verbose_name='数值：')),
                ('SW_type', models.CharField(max_length=25, verbose_name='设备类型')),
                ('SW_power', models.CharField(max_length=25, verbose_name='设备电量')),
                ('SW_status', models.CharField(max_length=25, verbose_name='设备状态')),
            ],
        ),
        migrations.DeleteModel(
            name='model_water',
        ),
    ]
