# Generated by Django 3.0 on 2021-12-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SW', '0002_auto_20211203_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_sensor',
            name='SW_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='设备ID'),
        ),
        migrations.AlterField(
            model_name='model_sensor',
            name='SW_num',
            field=models.CharField(max_length=50, verbose_name='数值'),
        ),
    ]
